var english = {
    "name": {
        "version": "2.0",
        "date": "2017-04-20",
        "name": "en"
    },
    "IOS": {
        "TT_SYSTEMUNLINK": "Printer not Connected",
        "TT_SYSTEMERROR": "Not Initialized",
        "TT_PREPARED": "Printer Ready",
        "TT_RUNING": "Printing in Progress",
        "TT_PAUSE": "Pause",
        "TT_NOZZLEERROR": "Nozzle Error",
        "TT_MOTIONERROR": "Motion System Error",
        "TT_FINISHED": "Printing Finished",
        "TT_USERSTOP": "Printing Stopped",
        "TT_TEMPHIGH": "Nozzle Temperature Too High",
        "TT_TEMPLOW": "Nozzle Temperature Too Low",
        "TT_WORKROOMHIGH": "Print Platform Temperature Too High",
        "TT_REVERSE_1": "reverse_1",
        "TT_REVERSE_2": "reverse_2",
        "TT_REVERSE_3": "reverse_3",
        "TT_REVERSE_4": "reverse_4",
        "TT_SYSTEMPOWERON": "System Powered ON",
        "TT_SDCARDERROR": "SD Card Error",
        "TT_SDWBERROR": "SD Card Write Error",
        "TT_SDRBERROR": "SD Card Read Error",
        "TT_SAVETOSD": "Data Saved on SD Card",
        "TT_JOGCMDERROR": "Jogging Instruction Error",
        "TT_COPYRIGHTZERO": "Copyright Restriction",
        "TT_PRINTTIMELIMIT": "Printing Number Restriction",
        "TT_COMMERROR": "Communication Error",
        "Please_choose_a_printer": "Please choose a printer",
        "Locals": "Locals",
        "Featured": "Featured",
        "More": "More",
        "Library": "Library",
        "DIY": "DIY",
        "Printer": "Printer",
        "Account": "Account",
        "Delete": "Delete",
        "Select_All": "Select All",
        "Cancel": "Cancel",
        "Delete_Selected_Models": "Delete Selected Models?",
        "Confirm": "Confirm",
        "Purchased": "Purchased",
        "Like_end": "Like",
        "Private": "Private",
        "Published": "Published",
        "Navigation": "Navigation",
        "Price": "Price",
        "All": "All",
        "Pay_Models": "Pay Models",
        "Free_Models": "Free Models",
        "Filter": "Filter",
        "Points": "Points",
        "Publish": "Publish",
        "Name": "Name",
        "Unlimited": "Unlimited",
        "Category": "Category",
        "Size": "Size",
        "Details": "Details",
        "Download_All": "Download All",
        "Like": "Like",
        "Buy": "Buy",
        "Cancel_Publish_Process": "Cancel Publish Process",
        "Printer_Status": "Printer Status",
        "Process": "Process",
        "Maintenance": "Maintenance",
        "Material": "Material",
        "Weight": "Weight",
        "Extrude": "Extrude",
        "Withdraw": "Withdraw",
        "Stop": "Stop",
        "Printer_List": "Printer List",
        "Please_Enter": "Please Enter",
        "Please_Enter_Password": "Please Enter Password",
        "Connecting": "Connecting",
        "Failed_to_Connect": "Failed to Connect",
        "Reprint": "Reprint",
        "Pause": "Pause",
        "Resume": "Resume",
        "Initalize_Printer": "Initalize Printer",
        "Customized_Material": "Customized Material",
        "Nozzle": "Nozzle(℃)",
        "Platform": "Platform(℃)",
        "Not_Logged_in": "Not Logged in",
        "My_Printer": "My Printer",
        "Settings": "Settings",
        "Username_or_Email": "Username / Email",
        "Password": "Password",
        "Login": "Login",
        "Forgot_Password": "Forgot Password?",
        "Sign_Up": "Sign Up",
        "Register_Username": "Username (3-20 Characters Starting with a Letter)",
        "Register_Email": "Email (Enter an Email Address)",
        "Register_Password": "Password (6-32 Characters)",
        "Register_ConPassword": "Confirm Password (Input Password Again)",
        "Register_Exist_Username": "Username Already Exists",
        "Register_Exist_Email": "Email Already Exists",
        "Register_Error_Username": "Invalid Username",
        "Register_Error_Email": "Invalid Email Address",
        "Register_Error_Password": "Invalid Password",
        "Register_Error_ConPassword": "Passwords Do Not Match",
        "Register_Check_Params": "Please Check The Input Parameters",
        "Register_Success_Text": "Registration is successful. An activation code has been sent to your email account. Please click the link in your email to activate your account.",
        "ResetPassword_Fial": "Email or Username Error",
        "ResetPassword_Success": "An email to reset your password has been sent to your email address.",
        "All_Printers": "All Printers",
        "Printer_Models": "Printer Models",
        "MyPrinter_CheckModel_Fail": "Failed to Recognize Printer Serial Number",
        "Serial_Number": "Serial Number",
        "Status": "Status",
        "Activation_Status": "Activation Status",
        "Binding_Status": "Binding Status",
        "Activate_end": "Activate",
        "Unactivated": "Unactivated",
        "Activate": "Activate",
        "Unbind": "Unbind",
        "Bind": "Bind",
        "Privacy_Policy": "Privacy Policy",
        "Clean_Up_Cache": "Clean Up Cache",
        "Sign_Out": "Sign Out",
        "Infill": "Infill",
        "Layer_Thickness": "Layer Thickness",
        "Quality": "Quality",
        "Preview": "Preview",
        "Print": "Print",
        "Shell": "Shell",
        "Surface": "Surface",
        "Please_Choose": "Please Choose",
        "Normal": "Normal",
        "Fine": "Fine",
        "Fast": "Fast",
        "Turbo": "Turbo",
        "H": "H",
        "M": "M",
        "S": "S",
        "g": "g",
        "NoticeText_SliceError": "ERROR: Slicing Error",
        "Progress": "Progress",
        "Initializing": "Initializing",
        "Use_Camera": "Use Camera",
        "Album": "Album",
        "NoticeText_OutBound": "ERROR: Model out of Bound",
        "NoticeText_NozzHeight": "ERROR: Nozzle Height Error. Valid Range (x - x)",
        "NoticeText_PrintRun": "Printing in Process. No Action Allowed.",
        "NoticeText_NoRepeatData": "No Saved Model to Repeat Printing",
        "NoticeText_TransError0": "Transmission is not completed",
        "NoticeText_TransError1": "System not ready",
        "NoticeText_TransError2": "The model has empty layers",
        "NoticeText_TransError3": "Part material insufficient for the print job",
        "NoticeText_TransError4": "Support material insufficient for the print job",
        "NoticeText_TransError5": "Fail to send cmd to printer",
        "NoticeText_TransError6": "Printer error",
        "NoticeText_TransError7": "Can not load buildstart program",
        "NoticeText_TransError8": "Lost WIFI packages",
        "NoticeText_TransError9": "Null temperature setting",
        "NoticeText_TransError10": "License verify failed",
        "Failed_to_load_model": "Failed to load model",
        "NoticeText_BuySuccess": "Purchase Successful",
        "NoticeText_BuyFail": "Purchase Failed. Please Try Again",
        "NoticeText_BuyPointError": "No Enough Points",
        "NoticeText_PublishName": "Please Enter Model Name",
        "NoticeText_PublishPoint": "Please Enter a Number",
        "No_more_data": "No More Data",
        "NoticeLink_NetworkError": "Network Problems, and Please Try Again Later",
        "NoticeLink_PasswordError": "ERROR: Incorrect Printer Password",
        "NoticeLink_AlreadyConnected": "ERROR: Printer is being used by other users",
        "NoticeLink_NotCert": "ERROR: Printer is not authorized",
        "NoticeLink_ConnectFail": "Cannot Connect to the Printer",
        "NoticeLink_NoRespone": "ERROR: Printer not Responding",
        "NoticeLink_Busy": "Printer Busy",
        "CustomMaterial_NameTips": "Please Enter 1-5 Characters",
        "CustomMaterial_NameRepeat": "ERROR: Matieral Name Duplicated",
        "CustomMaterial_TempTips": "Please Enter a Temperature Value(℃)",
        "CustomMaterial_NozzleTempTips": "ERROR: Temperature Value not Valid. Please enter (0-300)℃",
        "CustomMaterial_PlatTempTips": "ERROR: Temperature Value not Valid. Please enter (0-100)℃",
        "No_Printer_Found": "No Printer Found",
        "Printer_Status_Error": "ERROR: Printer Status Error",
        "Please_Connect_to_a_Printer": "Please Connect to a Printer",
        "Please_Enter_an_EmailvAddress": "Please Enter an Email Address",
        "Invalid_Email_Address": "Invalid Email Address",
        "Email_not_Valid_or_Failed_to_Send_Email": "Email not Valid or Failed to Send Email",
        "Failed_to_Pause_Print_Job": "Failed to Pause Print Job",
        "Failed_to_Resume_Print_Job": "Failed to Resume Print Job",
        "Confirm_to_stop_the_current_job": "Confirm to stop the current job?",
        "NoticeLink_CheckNetTip": "Please Check Your Network Setup, and Make Sure the APP Connects to the Same Router that the Printer is using",
        "ActivateTip": "Please activate the printer to use the full power of the printer.",
        "ActivateTip_ActivateFail": "Failed to activate the printer. Please contact the manufacturer.",
        "ActivateTip_ActivateSuccess": "Activation succeeded. Please restart the printer.",
        "Please_Close_the_Front_Door": "Please Close the Front Door.",
        "Print_Job_Stopped_at_Layer_Number": "Print Job Stopped at Layer No.",
        "Resume_the_Print_Job": ". Resume the Print Job?",
        "Data_Transmission_Failed": "ERROR: Data Transmission Failed. Try Again?",
        "Unnamed": "Unnamed",
        "Invalid_Activation_Key": "ERROR: Invalid Activation Key",
        "Factory_Activation_Status_Error": "ERROR: Factory Activation Status Error",
        "Activation_Failed_Invalid_Activation_Key": "ERROR: Activation Failed. Invalid Activation Key",
        "Activation_data_returned_from_server_failed": "ERROR: Activation data returned from server failed",
        "Server_failed_to_return_activation_code": "ERROR: Server failed to return activation code",
        "Failed_to_get_checksum_data_from_the_printer": "ERROR: Failed to get checksum data from the printer",
        "Failed_to_obtain_the_activation_status": "ERROR: Failed to obtain the activation status",
        "Cannot_Use_Special_Characters": "Cannot Use Special Characters",
        "User_Does_not_Exist": "User Does not Exist",
        "Please_Enter_Username_or_Email": "Please Enter Username/Email",
        "Please_Enter_Your_Password": "Please Enter Your Password",
        "User_Account_is_not_Activated": "User Account is not Activated",
        "Pull_down_to_refresh": "Pull down to refresh",
        "Release_to_refresh": "Release to refresh",
        "Refreshing": "Refreshing...",
        "Pull_up_to_load_more": "Pull up to load more...",
        "Release_to_load_more": "Release to load more...",
        "Loading": "Loading...",
        "No_Data": "No Data",
        "Slicing_in_progress_Cannot_load_models": "Slicing in progress. Cannot load models.",
        "No_material_detected_Please_reload_material": "No material detected. Please reload material.",
        "PrivacyText": "Please review Tiertime's Privacy Policy to know the details about Tiertime's data collection policy.You can choose to turn on or off the data collection optinos based on your preference.",
        "Singlepass_printing": "Single-pass printing",
        "Registration_meas_you_agree_with": "Registration meas you agree with",
        "Tiertime_End_User_Agreement": "Tiertime End User Agreement",
        "Under_Review": "Under Review",
        "Purchase_Type": "Purchase Type",
        "Customized": "Customized",
        "Local_Pictures": "Album",
        "Take_a_picture": "Camera",
        "Edit": "Edit",
        "Pen": "Pen",
        "Text": "Text",
        "Crop": "Crop",
        "Frame": "Frame",
        "Vase": "Vase",
        "NA": "N/A",
        "Base_Height": "Base Height",
        "Model_Height": "Model Height",
        "Add_Text": "Add Text",
        "Click_to_Enter_Text": "Click to Enter Text",
        "Keyboard": "Keyboard",
        "Font": "Font",
        "Toggle_color": "Toggle color",
        "Upload": "Upload",
        "Move": "Move",
        "Scale": "Scale",
        "Rotate": "Rotate",
        "Initial_View": "Initial View",
        "x": "x",
        "Y": "Y",
        "Z": "Z",
        "AboutUs": "About",
        "Current_Version": "Version",
        "WeChat_Official_Account": "WeChat official account",
        "Official_Website": "Official Website",
        "Software_License_Agreement": "Software License Agreement",
        "Copyright_Text": "Copyright © 2012-2017 TierTime.All right Reserved.",
        "Color_change":"Color Change",
        "floor":"Floor",
        "no_floor":"No Floor",
        "Punching":"Punching",
        "Adjustment":"Adjustment",
        "The_model_does_not_exist":"The model does not exist"
    }
}
