var english = {
    "name": {
        "version": "2.0",
        "date": "2017-07-28",
        "name": "en"
    },
    "IOS":{
    "TT_SYSTEMUNLINK": "Printer Offline",
    "TT_SYSTEMERROR": "Printer Uninitialized",
    "TT_PREPARED": "Printer Prepared",
    "TT_RUNING": "Printing",
    "TT_PAUSE": "Printer Suspended",
    "TT_NOZZLEERROR": "Nozzle Error",
    "TT_MOTIONERROR": "Motion System Error",
    "TT_FINISHED": "Print Finished",
    "TT_USERSTOP": "Print Stopped",
    "TT_TEMPHIGH": "Nozzle Temperature Too High",
    "TT_TEMPLOW": "Nozzle Temperature Too Low",
    "TT_WORKROOMHIGH": "Platform Temperature Too High",
    "TT_REVERSE_1": "reverse_1",
    "TT_REVERSE_2": "reverse_2",
    "TT_REVERSE_3": "reverse_3",
    "TT_REVERSE_4": "reverse_4",
    "TT_SYSTEMPOWERON": "System Powered ON",
    "TT_SDCARDERROR": "SD Card Error",
    "TT_SDWBERROR": "SD Card Write Error",
    "TT_SDRBERROR": "SD Card Read Error",
    "TT_SAVETOSD": "Saving Data to SD Card",
    "TT_JOGCMDERROR": "Jog CMD Error",
    "TT_COPYRIGHTZERO": "Copyright Restriction",
    "TT_PRINTTIMELIMIT": "Print Times Exceeded ",
    "TT_COMMERROR": "Communication Error",
    "Please_choose_a_printer": "Please Connect a Printer",
    "Locals": "Locals",
    "Featured": "Moshop",
    "More": "More",
    "Library": "Library",
    "DIY": "DIY",
    "Printer": "Printer",
    "Account": "Account",
    "Delete": "Delete",
    "Select_All": "Check All",
    "Cancel": "Cancel",
    "Delete_Selected_Models": "Are you sure you want to delete the selected model?",
    "Confirm": "Done",
    "Purchased": "Purchased",
    "Like_end": "Liked",
    "Private": "Private",
    "Published": "Published",
    "All": "All",
    "Pay_Models": ">1Point",
    "Free_Models": "1Point",
    "Filter": "Refine by",
    "Points": "Points",
    "Publish": "Publish",
    "Name": "Name",
    "Unlimited": "Unlimited",
    "Category": "Categories",
    "Size": "Size",
    "Download_All": "Download All",
    "Like": "Like",
    "Buy": "Buy",
    "UnPublish": "UnPublish",
    "Printer_Status": "Printer Status",
    "Process": "Operate",
    "Maintenance": "Maintenance",
    "Material": "Material",
    "Weight": "Weight",
    "Extrude": "Extrude",
    "Withdraw": "Withdraw",
    "Stop_Work": "Stop Work",
    "Printer_List": "Printer List",
    "Please_Enter": "Please Enter",
    "Connecting": "Connecting",
    "Failed_to_Connect": "Failed to Connect",
    "Reprint": "Reprint",
    "Pause": "Pause",
    "Resume": "Resume",
    "Initalize_Printer": "Initalize Printer",
    "Customized_Material": "Customized Material",
    "Nozzle": "Nozzle(℃)",
    "Platform": "Platform(℃)",
    "Not_Logged_in": "Not logged in",
    "My_Printer": "My Printers",
    "Settings": "Setting",
    "Username_or_Email": "Username / Email",
    "Password": "Password",
    "Login": "Sign in",
    "Forgot_Password": "Forgot Password",
    "Sign_Up": "Sign Up",
    "Register_Username": "Username (3-20 characters starting with a letter)",
    "Register_Email": "Email (Enter an email address)",
    "Register_Password": "Password (6-32 characters)",
    "Register_ConPassword": "Re-enter Password",
    "Register_Exist_Username": "Username Already Exits",
    "Register_Exist_Email": "Email Already Exists",
    "Register_Error_Username": "Invalid Username",
    "Register_Error_Password": "Invalid Password",
    "Register_Error_ConPassword": "Passwords Not Match",
    "Register_Success_Text": "Registration is successful. An activation code has been sent to your email account. Please click the link in your email to activate your account.",
    "ResetPassword_Fial": "Email or Username Error",
    "ResetPassword_Success": "An email to reset your password has been sent to your email address.",
    "All_Printers": "Choose a Printer",
    "Bind_Printers": "Bound",
    "Printer_Models": "Type",
    "MyPrinter_CheckModel_Fail": "----",
    "Serial_Number": "Serial Number",
    "Status": "Status",
    "Activation_Status": "Activation Status",
    "Binding_Status": "Binding Status",
    "Activate_end": "Activated",
    "Unactivated": "Unactivated",
    "Activate": "Activate",
    "Unbind": "Unbind",
    "Bind": "Bind",
    "Privacy_Policy": "UE Project",
    "Clean_Up_Cache": "Clean Up Cache",
    "Sign_Out": "Sign Out",
    "Infill": "Infill",
    "Layer_Thickness": "Layer Thickness",
    "Quality": "Quality",
    "Preview": "Preview",
    "Print": "Print",
    "Shell": "Shell",
    "Surface": "Surface",
    "Please_Choose": "Please Choose",
    "Normal": "Normal",
    "Fine": "Fine",
    "Fast": "Fast",
    "Turbo": "Turbo",
    "H": "H",
    "M": "M",
    "S": "S",
    "g": "g",
    "ItemSize":"Per Square Size",
    "SquareNumber":"Square number",
    "SquareSize":"Model Size",
    "NoticeText_SliceError": "ERROR: Slicing Error",
    "Initializing": "Initializing...",
    "Use_Camera": "Camera",
    "Album": "Album",
    "NoticeText_OutBound": "ERROR: Model Beyonds Printer Boundary",
    "NoticeText_NozzHeight": "ERROR: Nozzle Height Error. Valid Range:",
    "NoticeText_PrintRun": "Printing!!! AND-NOT operation!",
    "NoticeText_NoRepeatData": "Have no Model for Reprinting",
    "NoticeText_TransError0": "Transmission is not finished",
    "NoticeText_TransError1": "System has not prepared",
    "NoticeText_TransError2": "The model has empty layers",
    "NoticeText_TransError3": "Part material insufficient for the print job",
    "NoticeText_TransError4": "Support material insufficient for the print job",
    "NoticeText_TransError5": "Fail to send CMD to printer",
    "NoticeText_TransError6": "Printer error",
    "NoticeText_TransError7": "Fail to load buildstart program",
    "NoticeText_TransError8": "Lost WIFI packages",
    "NoticeText_TransError9": "Have not set nozzle or platform temperature",
    "NoticeText_TransError10": "Verification failed",
    "Failed_to_load_model": "Failed to load model",
    "NoticeText_BuySuccess": "Purchase Successful",
    "NoticeText_BuyFail": "Purchase Failed. Please Try Again",
    "NoticeText_BuyPointError": "No Enough Points",
    "NoticeText_PublishName": "1-32 Characters",
    "NoticeText_PublishPoint": "Please Enter a Number",
    "No_data": "No Data",
    "NoticeLink_NetworkError": "Network Problems, and Please Try Again Later",
    "NoticeLink_PasswordError": "ERROR: Incorrect Printer Password",
    "NoticeLink_AlreadyConnected": "ERROR: Printer is being used by another user",
    "NoticeLink_NotCert": "ERROR: Printer is not authorized",
    "NoticeLink_ConnectFail": "Cannot Connect to the Printer",
    "NoticeLink_NoRespone": "ERROR: Printer not Responding",
    "NoticeLink_Busy": "Printer Busy",
    "CustomMaterial_NameTips": "1-5 Characters(Letters, Numbers and '+' '-' '_')",
    "CustomMaterial_NameRepeat": "Matieral Name Duplicated",
    "CustomMaterial_TempTips": "Please Enter a Temperature Value(℃)",
    "CustomMaterial_NozzleTempTips": "Temperature(0-300)℃",
    "CustomMaterial_PlatTempTips": "Temperature(0-100)℃",
    "Printer_Status_Error": "ERROR: Printer Status Error",
    "Invalid_Email_Address": "Invalid Email Address",
    "Email_not_Valid_or_Failed_to_Send_Email": "Failed to Send Email",
    "Failed_to_Pause_Print_Job": "Failed to Pause",
    "Failed_to_Resume_Print_Job": "Failed to Resume ",
    "Confirm_to_stop_the_current_job": "Confirm to stop the current job?",
    "NoticeLink_CheckNetTip": "Please Check Your Network Setting, and Make Sure the APP Connects to the Same Router that the Printer is using.",
    "ActivateTip": "Please activate the printer to get the full power of the printer.",
    "ActivateTip_ActivateFail": "Failed to activate the printer. Please contact the manufacturer.",
    "ActivateTip_ActivateSuccess": "Activation succeeded. Please restart the printer.",
    "Please_Close_the_Front_Door": "Please Close the Front Door.",
    "Print_Job_Stopped_at_Layer_Number": "Print Job Stopped at Layer No.",
    "Resume_the_Print_Job": ",Resume the Print Job?",
    "Invalid_Activation_Key": "ERROR: Invalid Activation Key",
    "Factory_Activation_Status_Error": "ERROR: Factory Activation Status Error",
    "Activation_Failed_Invalid_Activation_Key": "ERROR: Activation Failed. Invalid Activation Key",
    "Activation_data_returned_from_server_failed": "ERROR: Activation data returned from server failed",
    "Server_failed_to_return_activation_code": "ERROR: Server failed to return activation code",
    "Failed_to_get_checksum_data_from_the_printer": "ERROR: Failed to get checksum data from the printer",
    "Failed_to_obtain_the_activation_status": "ERROR: Failed to obtain the activation status",
    "Cannot_Use_Special_Characters": "Cannot Use Special Characters",
    "User_Account_is_not_Activated": "User Account is not Activated",
    "Pull_down_to_refresh": "Pull down to refresh",
    "Release_to_refresh": "Release to refresh",
    "Refreshing": "Refreshing...",
    "Pull_up_to_load_more": "Pull up to load more...",
    "Release_to_load_more": "Release to load more...",
    "Loading": "Loading...",
    "Slicing_in_progress_Cannot_load_models": "Slicing! Cannot load models.",
    "No_material_detected_Please_reload_material": "No material detected. Please reload material.",
    "PrivacyText": "Please review Tiertime's Privacy Policy to know the details about Tiertime's data collection policy.You can choose to turn on or off the data collection optinos based on your preference.",
    "Singlepass_printing": "One time",
    "Registration_meas_you_agree_with": "Registration meas you agree with",
    "Tiertime_End_User_Agreement": "Tiertime End User Agreement",
    "Under_Review": "Under Review",
    "Purchase_Type": "Tariff packages",
    "Customized": "Customized",
    "Edit": "Edit",
    "Puzzle":"Puzzle",
    "Pen": "Pen",
    "Text": "Text",
    "Crop": "Crop",
    "image_relative":"Relative",
    "NA": "----",
    "Add_Text": "Add Text",
    "Click_to_Enter_Text": "Click to Enter Text",
    "Keyboard": "Keyboard",
    "Font": "Font",
    "Upload": "Upload",
    "Scale": "Scale",
    "X": "X",
    "Y": "Y",
    "Z": "Z",
    "To_print":"Preview",
    "AboutUs": "About",
    "Current_Version": "Version",
    "WeChat_Official_Account": "WeChat Account",
    "Official_Website": "Official Website",
    "Software_License_Agreement": "Software License Agreement",
    "Copyright_Text": "Copyright © 2012-2017 TierTime.All right Reserved.",
    "floor": "Floor",
    "no_floor": "No Floor",
    "Punching": "Puncher",
    "Adjustment": "Adjustment",
    "ModelName":"Model Name",
    "UploadModel":"Upload Model",
    "Width":"Length",
    "Height":"Width",
    "Depth":"Depth",
    "Input_Error":"Number",
    "ModelAdjustment":"Edit",
    "The_model_does_not_exist": "The model does not exist",
    "Binded":"Binded",
    "Choose_material":"Choose Material",
    "Material_name":"Material Name",
    "Please_enter_the_weight":"Please enter the weight",
    "Please_enter_a_valid_number":"Please enter a valid number",
    "Preview_print":"Preview Print",
    "Slicing":"Slicing",
    "Transport":"Sending",
    "Counting":"Counting",
    "Select_the_print_location":"Select the print location",
    "User_does_not_exist":"User does not exist",
    "Wrong_password":"Password is not correct",
    "Login_fail_Text":"Failed! please try again later",
    "Confirm_to_delete_the_cache":"Are you sure you want to delete",
    "The_currently_connected_printer":"Connecting",
    "Printer_information":"Printer Information",
    "Tiertime_Privacy_Agreement":"TierTime Privacy Agreement",
    "Remaining_Prints":"Remaining prints",
    "times":"times",
    "Successful_publish":"Publish Successfully",
    "Successful_upload":"Upload Successfully",
    "ErrorText_timeout":"Upload Error:Out of time",
    "Action_failed_please_try_later":"Action failed,please try later",
    "Stop_Printing":"Stop Printing",
    "ErrorText_MaterialShortage":"Printer is short of material. Still continue?",
    "ErrorText_SupportShortage":"Printer is short of support material. Still continue?",
    "ErrorText_TransferFailed":"Data transfer failed. Try again?",
    "ErrorText_UnknowError":"Unknow Error",
    "Print_Time":"Print Time:",
    "Material_Consumption":"Material Consumption:",
    "ErrorText_IncorrectMaterial":"Incorrect material",
    "ErrorText_Printer_SN_Error":"Printer SN error",
    "Join":"Join",
    "Package":"Files",
    "Progress_Rate":"Progress",
    "Import_Successful":"Model has been imported. Open it now?",
    "Open":"Open",
    "OpenFail_Slice":"Open Model ERROR: can not load models when slicing!",
    "OpenFail_Trans":"Open Model ERROR: can not load  models when transporting!",
    "RegisterFail_hasExist":"Registration failed, username or email already exists!",
    "No_network":"No Networking, please connect to the Internet.",
    "Error_ModelData":"Construct 3D model fail!",
    "Demonstration":"Demonstration",
    "MyProfile":"My Profile",
    "ModelDetails":"Model Details",
    "Description":"Descriptions",
    "Enter_Description":"Please enter a model description",
    "INCHTOMM":"Model has enlarged 25.4 times",
    "Allow_album_access":"Allow album access",
    "Allow_camera_access":"Allow camera access",
    "album_privacy_text":"APP don't have the premission to access the album, allow access to the album in your device's settings. ",
    "carema_privacy_text":"APP don't have the premission to access the carema, allow access to the carema in your device's settings.",
    "Print_count": "Print Times",
    "UPS_Model_validation_failure":"ERROR: Model validation failure",
    "NoticeText_PublishNameNull":"The model name cannot be empty",
    "Model_publish_limited": "Unlimited print prices must be higher than a single print price",
    "Printer_disconnect":"The printer is disconnected",
    "Nozzle_diameter": "Nozzle Diam",
    "Compensation_height": "Nozzle offset",
    "Choose_floor": "Print Board",
    "Feedback":"Feedback",
    "fb_Choose_type":"What dose your feedback relate to?",
    "fb_Add_text":"Add text",
    "fb_Text_tips":"Please type your feedbacks(maximum 400 characters)",
    "fb_Email_title":"Contact infomation(optional)",
    "fb_Email_placeholder":"Enter your Email address",
    "fb_SN_title":"Printer SN(optional)",
    "fb_SN_placeholder":"The serial number of your printer",
    "fb_Add_images":"Add images(optional)",
    "fb_opinion":"Question/Opinion",
    "fb_App_issue":"App issue",
    "fb_Printer_issue":"Printer issue",
    "fb_Others":"Other"
}
}
